name: "Setup MSVC"
description: "Setup Microsoft Visual C++ compiler"

inputs:
  arch:
    description: "Hardware architecture"
    required: true
    default: "x64"
  toolset:
    description: "Toolset version"
    required: true
    default: "14.16"

runs:
  using: "composite"
  steps:
    -
      name: Set MSVC toolchain (v9.0)
      shell: pwsh
      run: |
        & "${{ github.action_path }}\scripts\install_msvc90.ps1"
        & "${{ github.action_path }}\scripts\start_msvc.ps1" ${{ inputs.arch }} v90 |
            ForEach-Object { Write-Output $_ >> $env:GITHUB_ENV }
      if: ${{ contains(fromJson('["9", "9.0"]'), inputs.toolset) }}
    -
      name: Set MSVC toolchain (v14.0)
      shell: pwsh
      run: |
        & "${{ github.action_path }}\scripts\start_msvc.ps1" ${{ inputs.arch }} v140 |
            ForEach-Object { Write-Output $_ >> $env:GITHUB_ENV }
      if: ${{ contains(fromJson('["14", "14.0"]'), inputs.toolset) }}
    -
      name: Set MSVC toolchain (v14.1+)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ inputs.architecture }}
        toolset: ${{ inputs.toolset }}
      if: ${{ ! contains(fromJson('["9", "9.0", "14", "14.0"]'), inputs.toolset) }}
